package net.opencraft.client.renderer;

import static org.lwjgl.glfw.GLFW.glfwGetPrimaryMonitor;
import static org.lwjgl.glfw.GLFW.glfwGetVideoMode;

import java.awt.Dimension;

import org.lwjgl.glfw.GLFWVidMode;

/**
 * <h1>Monitor class</h1>
 * The monitor class help us to see any monitor configuration.
 */
public final class Monitor {

	/**
	 * Monitor's id <br />
	 * <i>(Generated by GLFW)</i>
	 */
	private final long id;

	/**
	 * Instances a {@code Monitor} class.
	 * @param id the monitor's id
	 */
	private Monitor(final long id) {
		this.id = id;
	}

	/**
	 * @return the primary/default monitor
	 */
	public static Monitor getPrimaryMonitor() {
		return new Monitor(glfwGetPrimaryMonitor());
	}

	/**
	 * @return the monitor size
	 */
	public Dimension size() {
		GLFWVidMode videoMode = getVideoMode();
		if (videoMode == null)
			throw new RuntimeException("Invalid monitor configuration!");
		
		return new Dimension(videoMode.width(), videoMode.height());
	}

	/**
	 * @return the monitor width
	 */
	public int width() {
		return size().width;
	}

	/**
	 * @return the monitor height
	 */
	public int height() {
		return size().height;
	}

	/**
	 * @return the video mode generated by {@code GLFW}.
	 */
	private GLFWVidMode getVideoMode() {
		return glfwGetVideoMode(id);
	}

	/**
	 * @return the monitor's id
	 */
	public long getId() {
		return id;
	}

}
